---
- name: Install NodeSource repository key
  apt_key:
    id: 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    keyring: /etc/apt/trusted.gpg.d/nodesource.gpg
    state: present

- name: Install NodeSource package repository
  apt_repository:
    repo: deb https://deb.nodesource.com/node_{{ nodesource_version }}.x {{ ansible_distribution_release }} main
    filename: nodesource
    state: present

- name: Install Node.js
  apt:
    name: "{{ nodesource_packages|flatten }}"
    state: "{{ nodesource_packages_state }}"
    update_cache: yes
