---
- name: Verify
  hosts: all
  tasks:
    - name: Ensure Node.js is installed
      stat:
        path: /usr/sbin/node
      register: result
      changed_when: false
      failed_when: result.stat.isreg is not defined or not result.stat.isreg
